### ISSUE TITLE
Error contao-lottie-player and Contao 5.1.8

### ISSUE THREAD

**Issue by sdahlmann** [inspiredminds/contao-lottie-player#3]
When I want to create a Lottie element with Contao 5.1.8 I get the following error message: "Tried to list template options for the modern fragment type "content_element/lottie_player" but could not find any template. In case you wanted to use the legacy type " ce_lottie_player", define it explicitly in the "template" property of your controller's service tag/attribute." No additional extensions are installed in the test installation. With another installation, where I just noticed the error first, I get the same error message. Runs on PHP 8.2.6 and MySQ 5.7. Can you possibly please correct the error. Thank you in advance.
---
Wenn ich ein Lottie Element erstellen möchte unter Contao 5.1.8 bekomme ich folgende Fehlermeldung: "Tried to list template options for the modern fragment type "content_element/lottie_player" but could not find any template. In case you wanted to use the legacy type "ce_lottie_player", define it explicitly in the "template" property of your controller's service tag/attribute." Bei der Test-Installation sind keine weiteren Erweiterungen installiert. Bei einer anderen Installation, wo mir der Fehler eben zuerst aufiel, bekomme ich die selbe Fehlermeldung. Läuft unter PHP 8.2.6 und MySQ 5.7. Können Sie eventl. bitte den Fehler korriegieren. Vielen Dank dafür schon im Voraus.

**Comment by sdahlmann** [comment]
![Lottie-Player_Error](https://github.com/inspiredminds/contao-lottie-player/assets/17680074/cec1236b-d61c-4989-996a-ffb7b4388bc5)

**Comment by fritzmg** [comment]
Fixed in `1.3.2` 👍
