### ISSUE TITLE
Lottie-Player not loading | Contao 4.13

### ISSUE THREAD

**Issue by Patric96** [inspiredminds/contao-lottie-player#4]
I tried to use the Lottie-Extension on a Website of mine and experienced a weird behaviour. 
The player element is sometimes showing, sometimes completely removed of the DOM and sometimes its flashing shortly and disappears. I tried the two available templates but the bug consists. Do you know what is going wrong here?
https://www.skve.de/speicherkraftwerk/biogas

**Comment by fritzmg** [comment]
No idea why that would happen. May be your https://www.skve.de/files/images/lottie/biogas.json requires a newer Lottie version? You could test by replacing the files in `vendor/inspiredminds/contao-lottie-player/src/Resources/public` with newer versions.

**Comment by Patric96** [comment]
Unfortunately, this is not the solution. I tried multiple Versions of lottie-player.js.
I also tried an animation directly from lottie, ending up with the same problem. In one of five refreshes, the animation is perfectly playing. The other ones result in showing it for 0,5 seconds or not showing at all.

**Comment by Patric96** [comment]
Ok, i can now say what causes the bug - even if i don't know why.
I have jquery activated with the template "j_accordion". After deactivating jquery, your extension works like expected.
